/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Hosu35HioasssIndexRouteImport } from './routes/Hosu35Hioasss.index'
import { Route as Hosu35HioasssDashboardRouteImport } from './routes/Hosu35Hioasss.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Hosu35HioasssIndexRoute = Hosu35HioasssIndexRouteImport.update({
  id: '/Hosu35Hioasss/',
  path: '/Hosu35Hioasss/',
  getParentRoute: () => rootRouteImport,
} as any)
const Hosu35HioasssDashboardRoute = Hosu35HioasssDashboardRouteImport.update({
  id: '/Hosu35Hioasss/dashboard',
  path: '/Hosu35Hioasss/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Hosu35Hioasss/dashboard': typeof Hosu35HioasssDashboardRoute
  '/Hosu35Hioasss/': typeof Hosu35HioasssIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Hosu35Hioasss/dashboard': typeof Hosu35HioasssDashboardRoute
  '/Hosu35Hioasss': typeof Hosu35HioasssIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Hosu35Hioasss/dashboard': typeof Hosu35HioasssDashboardRoute
  '/Hosu35Hioasss/': typeof Hosu35HioasssIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Hosu35Hioasss/dashboard' | '/Hosu35Hioasss/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Hosu35Hioasss/dashboard' | '/Hosu35Hioasss'
  id: '__root__' | '/' | '/Hosu35Hioasss/dashboard' | '/Hosu35Hioasss/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Hosu35HioasssDashboardRoute: typeof Hosu35HioasssDashboardRoute
  Hosu35HioasssIndexRoute: typeof Hosu35HioasssIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Hosu35Hioasss/': {
      id: '/Hosu35Hioasss/'
      path: '/Hosu35Hioasss'
      fullPath: '/Hosu35Hioasss/'
      preLoaderRoute: typeof Hosu35HioasssIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Hosu35Hioasss/dashboard': {
      id: '/Hosu35Hioasss/dashboard'
      path: '/Hosu35Hioasss/dashboard'
      fullPath: '/Hosu35Hioasss/dashboard'
      preLoaderRoute: typeof Hosu35HioasssDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Hosu35HioasssDashboardRoute: Hosu35HioasssDashboardRoute,
  Hosu35HioasssIndexRoute: Hosu35HioasssIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
